name: Manually trigger for deploy to Firebase
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - uses: actions/cache@v4.2.4
        id: firebase-bin
        with:
          path: ./firebase_bin
          key: ${{ runner.os }}
          restore-keys: |
            ${{ runner.os }}

      - uses: bahmutov/npm-install@HEAD
        # with:
        #   working-directory: frontend
      
      - name: Download firebase binary if not in cache or os change
        if: steps.firebase-bin.outputs.cache-hit != 'true'
        run: |
          curl -Lo ./firebase_bin https://firebase.tools/bin/linux/latest
        
      - name: Build frontend dependencies
        run: yarn build
        # working-directory: frontend
        
      # - name: Copy frontend to public firabase structure
      #   run: cp -a frontend/dist/. public/
      
      - name: Deploy to Firebase
        run: |
          chmod 755 ./firebase_bin
          ./firebase_bin deploy --only hosting --token ${{ secrets.FIREBASE_TOKEN }}

      
      
